//
// Generated file, do not edit! Created by nedtool 5.5 from transaction.msg.
//

#ifndef __PECSN_PROJECT_TRANSACTION_M_H
#define __PECSN_PROJECT_TRANSACTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace pecsn_project {

/**
 * Class generated from <tt>transaction.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Transaction
 * {
 *     int id;
 *     int gate;
 * }
 * </pre>
 */
class Transaction : public ::omnetpp::cMessage
{
  protected:
    int id;
    int gate;

  private:
    void copy(const Transaction& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Transaction&);

  public:
    Transaction(const char *name=nullptr, short kind=0);
    Transaction(const Transaction& other);
    virtual ~Transaction();
    Transaction& operator=(const Transaction& other);
    virtual Transaction *dup() const override {return new Transaction(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getGate() const;
    virtual void setGate(int gate);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Transaction& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Transaction& obj) {obj.parsimUnpack(b);}

} // namespace pecsn_project

#endif // ifndef __PECSN_PROJECT_TRANSACTION_M_H

